### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by luy98** [sparrow-js/ant-codeAI#1]
Application error: a client-side exception has occurred (see the browser console for more information).

可能是什么原因？配置的是三方接口地址和APIKEY

**Comment by sparrow-js** [comment]
> Application error: a client-side exception has occurred (see the browser console for more information).
> 
> 可能是什么原因？配置的是三方接口地址和APIKEY

应该是报错了，打开调试工具console里的输出错误帮截图我修复下

**Comment by luy98** [comment]
![image](https://github.com/sparrow-js/ant-codeAI/assets/102730238/55ed97b2-015e-46cf-a07c-68c40a856ba2)
感觉是跟配置的接口地址有关系？
![image](https://github.com/sparrow-js/ant-codeAI/assets/102730238/85478788-352d-4b59-8480-305fdc8bb57b)

**Comment by sparrow-js** [comment]
报错兼容改好了，看着是你这个代理请求不到数据造成的，项目直接用的自定义的proxy url和key请求的，没有做其他操作

**Comment by luy98** [comment]
这个版本可以了，还是用的这个URL和KEY

**Comment by luy98** [comment]
vue系列的两个，看不到效果，是空白的，比如这个：
<html>
<head>
  <meta charset="UTF-8">
  <title>Vue/Tailwind App</title>
  <script src="https://registry.npmmirror.com/vue/3.3.11/files/dist/vue.global.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></link>
  <style>
    body {
      font-family: 'Inter', sans-serif;
    }
  </style>
</head>
<body>
  <div id="app"></div>
  <script type="module">
    const { createApp } = Vue;

    createApp({
      template: `
        <div class="bg-white shadow rounded-lg p-6 w-full max-w-sm mx-auto mt-12">
          <div class="flex justify-between items-center border-b pb-4">
            <div class="text-lg font-semibold">全部</div>
            <div class="text-sm">44</div>
            <button class="text-gray-400 hover:text-gray-600">
              <i class="fas fa-ellipsis-h"></i>
            </button>
          </div>
          <div class="flex items-center justify-between py-4 border-b">
            <button class="text-blue-600 text-lg font-semibold flex items-center">
              <i class="fas fa-plus mr-2"></i>新建分组
            </button>
            <button class="text-gray-500 px-4 py-2 rounded-lg border bg-gray-200 
                       hover:bg-gray-300 text-sm font-semibold">
              Shift + N
            </button>
          </div>
          <div class="flex items-center justify-between py-4">
            <button class="text-gray-500 text-lg font-semibold flex items-center">
              <i class="far fa-folder mr-2"></i>未分组
            </button>
            <div class="text-sm">44</div>
          </div>
        </div>
      `
    }).mount('#app');
  </script>
</body>
</html>
但是把其中的template代码单独拿出来解析，是可以看到效果的

![image](https://github.com/sparrow-js/ant-codeAI/assets/102730238/453c1e57-5aab-4fcb-a988-f1ca5911ef68)

![image](https://github.com/sparrow-js/ant-codeAI/assets/102730238/3580826b-9b9e-4581-82d3-373ef70267b4)

**Comment by luy98** [comment]
看到了，是vue的cdn地址有问题，改为：  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>就可以了，其他的也可以

**Comment by sparrow-js** [comment]
> 看到了，是vue的cdn地址有问题，改为： <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>就可以了，其他的也可以。另外element的也是cdn有问题

前一阵改成国内的cdn了，unpkg.com有时候请求不到也是麻烦，我想想怎么改下
