### ISSUE TITLE
大佬，启动不了了

### ISSUE THREAD

**Issue by 1378056564** [sparrow-js/ant-codeAI#18]
昨天还可以启动
今天npm i之后启动就卡在readying 5.65s.....
请问是哪里出了问题呢

**Comment by sparrow-js** [comment]
> 昨天还可以启动 今天npm i之后启动就卡在readying 5.65s..... 请问是哪里出了问题呢

我这没问题啊，有没有报错信息，或者删除node_modules，重新 pnpm i 下

**Comment by 1378056564** [comment]
![image](https://github.com/sparrow-js/ant-codeAI/assets/66588374/2eb23a7a-e0e7-4901-9fc6-50ee19f71d44)
![image](https://github.com/sparrow-js/ant-codeAI/assets/66588374/7714efce-7ae8-417b-9b88-c95b170022f4)
就没反应，也没有什么报错

**Comment by 1378056564** [comment]
咦，我知道原因了。感谢~希望可以出个有后台版本以及可以更新啥的0.0挺好用的

**Comment by sparrow-js** [comment]
> 咦，我知道原因了。感谢~希望可以出个有后台版本以及可以更新啥的0.0挺好用的

希望更新什么？
