### ISSUE TITLE
Module not found: Can't resolve 'tailwind-merge'

### ISSUE THREAD

**Issue by cong1999** [sparrow-js/ant-codeAI#25]
node version:  v18.19.0
npm version: 10.2.3
platform: windows x86-64
error log:
./components/lib/utils.ts:2:0
Module not found: Can't resolve 'tailwind-merge'
  1 | import { type ClassValue, clsx } from "clsx";
> 2 | import { twMerge } from "tailwind-merge";
  3 |
  4 | export function cn(...inputs: ClassValue[]) {
  5 |   return twMerge(clsx(inputs));

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./components/components/ui/dialog.tsx
./components/components/OnboardingNote.tsx
./pages/index.tsx

**Comment by sparrow-js** [comment]
Reinstall？ pnpm i
